name: Miri

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Prepare Miri
        run: cargo miri setup
      - name: Test sticky cleanup without leaks
        run: |
          cargo miri test --no-default-features sticky::
          cargo miri test --all-features sticky::
      - name: Test without default features
        run: cargo miri test --no-default-features
        env:
          MIRIFLAGS: -Zmiri-ignore-leaks
      - name: Test default features
        run: cargo miri test
        env:
          MIRIFLAGS: -Zmiri-ignore-leaks
      - name: Test all features
        run: cargo miri test --all-features
        env:
          MIRIFLAGS: -Zmiri-ignore-leaks
